services:
  # Backend API Service
  - type: web
    name: bookmyshow-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_REDIS_HOST
        sync: false
      - key: SPRING_REDIS_PORT
        sync: false
      - key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        sync: false
    healthCheckPath: /actuator/health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: bookmyshow-frontend
    env: docker
    dockerfilePath: ./movie-booking-frontend/Dockerfile
    dockerContext: ./movie-booking-frontend
    plan: free
    region: oregon
    envVars:
      - key: REACT_APP_API_URL
        value: https://bookmyshow-backend.onrender.com
    autoDeploy: true

  # Redis Service (if needed)
  - type: redis
    name: bookmyshow-redis
    plan: free
    region: oregon
    maxmemoryPolicy: allkeys-lru 